name: Build and Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

  build:
    name: Build Project
    strategy:
      matrix:
        os: [ Windows, MacOS, Ubuntu ]
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo ${{ matrix.os }}

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
