name: Build and Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

  build:
    name: Build Project
    strategy:
      matrix:
        os: [ Windows, MacOS, Ubuntu ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo ${{ matrix.os }}

  test:
    name: Sanity Test
    strategy:
      matrix:
        os: [ Windows, MacOS, Ubuntu ]
    runs-on: ubuntu-latest
    needs: [ lint, build ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo ${{ matrix.os }}

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: echo "Configure AWS credentials"

    - name: Login to Amazon ECR
      run: echo "Login to Amazon ECR"

    - name: Fill in the new image ID in the Amazon ECS task definition
      run: echo "Fill in the new image ID in the Amazon ECS task definition"

    - name: Deploy Amazon ECS task definition
      run: echo "Deploy Amazon ECS task definition"
